---
# Organization to pull metrics from
organization: 'WorldHealthOrganization'

# Start date to pull metrics from
since: '2020-01-01'

# GitHub Pages path to the repository
# Used for handling relative paths for assets
basePath: '/world-health-org-metrics'
